In [4]:
import pandas
df = pandas.read_csv("new.csv")

In [5]:
df

,Rank,Major,Early Career Pay,Mid Career Pay,% High Meaning
0,1,Petroleum Engineering,$97500,$212500,61%
1,2,Operations Research & Industrial Engineering,$98300,$191800,21%
2,3,Interaction Design,$74700,$173600,54%
3,4,Applied Economics and Management,$76500,$164400,54%
4,5,Building Science,$69000,$163100,47%
...,...,...,...,...,...
818,795,Equine Studies,$40300,$52500,50%
819,796,Addictions Counseling,$45900,$52200,78%
820,797,Nonprofit Administration,$42800,$52100,72%
821,798,Early Childhood Education,$41700,$50600,77%
822,799,Metalsmithing,$44700,$44900,36%